create table products (
	product_id INT,
	category VARCHAR(50),
	price VARCHAR(50)
);
insert into products (product_id, category, price) values (1, 'Automotive', 49.99);
insert into products (product_id, category, price) values (2, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (3, 'Automotive', 15.99);
insert into products (product_id, category, price) values (4, 'Food - Condiments', 3.99);
insert into products (product_id, category, price) values (5, 'Kitchen', 15.99);
insert into products (product_id, category, price) values (6, 'Food - Canned Goods', 2.79);
insert into products (product_id, category, price) values (7, 'Health', 19.99);
insert into products (product_id, category, price) values (8, 'Audio', 59.99);
insert into products (product_id, category, price) values (9, 'Accessories', 34.99);
insert into products (product_id, category, price) values (10, 'Food - Prepared Foods', 8.99);
insert into products (product_id, category, price) values (11, 'Clothing - Bottoms', 54.99);
insert into products (product_id, category, price) values (12, 'Smart Home', 99.99);
insert into products (product_id, category, price) values (13, 'Fitness', 29.99);
insert into products (product_id, category, price) values (14, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (15, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (16, 'Fitness', 49.99);
insert into products (product_id, category, price) values (17, 'Smart Home', 19.99);
insert into products (product_id, category, price) values (18, 'Kitchen', 59.99);
insert into products (product_id, category, price) values (19, 'Food - Nuts', 4.29);
insert into products (product_id, category, price) values (20, 'Home', 34.99);
insert into products (product_id, category, price) values (21, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (22, 'Food - Prepared Meals', 6.49);
insert into products (product_id, category, price) values (23, 'Home', 45);
insert into products (product_id, category, price) values (24, 'Tools', 24.99);
insert into products (product_id, category, price) values (25, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (26, 'Music', 359.99);
insert into products (product_id, category, price) values (27, 'Automotive', 14.99);
insert into products (product_id, category, price) values (28, 'Food - Pasta', 6.49);
insert into products (product_id, category, price) values (29, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (30, 'Home', 24.99);
insert into products (product_id, category, price) values (31, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (32, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (33, 'Home', 34.99);
insert into products (product_id, category, price) values (34, 'Food - Snacks', 3.59);
insert into products (product_id, category, price) values (35, 'Food - Salads', 5.99);
insert into products (product_id, category, price) values (36, 'Food - Vegetables', 3.79);
insert into products (product_id, category, price) values (37, 'Books', 39.99);
insert into products (product_id, category, price) values (38, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (39, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (40, 'Home', 24.99);
insert into products (product_id, category, price) values (41, 'Home Improvement', 199.99);
insert into products (product_id, category, price) values (42, 'Clothing - Dresses', 49.99);
insert into products (product_id, category, price) values (43, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (44, 'Kitchen', 44.99);
insert into products (product_id, category, price) values (45, 'Clothing - Tops', 22.99);
insert into products (product_id, category, price) values (46, 'Art Supplies', 19.99);
insert into products (product_id, category, price) values (47, 'Food - Condiments', 5.49);
insert into products (product_id, category, price) values (48, 'Office', 99.99);
insert into products (product_id, category, price) values (49, 'Food - Meat', 8.49);
insert into products (product_id, category, price) values (50, 'Fitness', 29.99);
insert into products (product_id, category, price) values (51, 'Food - Cooking Essentials', 2.49);
insert into products (product_id, category, price) values (52, 'Fitness', 15.99);
insert into products (product_id, category, price) values (53, 'Fitness', 12.99);
insert into products (product_id, category, price) values (54, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (55, 'Food - Canned Goods', 1.49);
insert into products (product_id, category, price) values (56, 'Food - Cooking Oil', 6.99);
insert into products (product_id, category, price) values (57, 'Outdoor', 34.99);
insert into products (product_id, category, price) values (58, 'Food - Beverages', 3.99);
insert into products (product_id, category, price) values (59, 'Health', 59.99);
insert into products (product_id, category, price) values (60, 'Food - Condiments', 1.99);
insert into products (product_id, category, price) values (61, 'Food - Jams & Jellies', 3.59);
insert into products (product_id, category, price) values (62, 'Food - Meal Kits', 7.99);
insert into products (product_id, category, price) values (63, 'Audio', 19.99);
insert into products (product_id, category, price) values (64, 'Food - Condiments', 2.29);
insert into products (product_id, category, price) values (65, 'Garden', 22.99);
insert into products (product_id, category, price) values (66, 'Food - Grains', 2.99);
insert into products (product_id, category, price) values (67, 'Food - Frozen Food', 8.99);
insert into products (product_id, category, price) values (68, 'Tools', 199.99);
insert into products (product_id, category, price) values (69, 'Art Supplies', 19.99);
insert into products (product_id, category, price) values (70, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (71, 'Food - Grains', 3.59);
insert into products (product_id, category, price) values (72, 'Travel', 29.99);
insert into products (product_id, category, price) values (73, 'Pets', 39.99);
insert into products (product_id, category, price) values (74, 'Pets', 109.99);
insert into products (product_id, category, price) values (75, 'Books', 14.99);
insert into products (product_id, category, price) values (76, 'Clothing - Shoes', 99.99);
insert into products (product_id, category, price) values (77, 'Health', 22.99);
insert into products (product_id, category, price) values (78, 'Toys', 24.99);
insert into products (product_id, category, price) values (79, 'Travel', 12.99);
insert into products (product_id, category, price) values (80, 'Food - Dairy', 4.49);
insert into products (product_id, category, price) values (81, 'Art Supplies', 79.99);
insert into products (product_id, category, price) values (82, 'Food - Breakfast', 2.99);
insert into products (product_id, category, price) values (83, 'Outdoor', 109.99);
insert into products (product_id, category, price) values (84, 'Food - Salads', 4.99);
insert into products (product_id, category, price) values (85, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (86, 'Fitness', 14.99);
insert into products (product_id, category, price) values (87, 'Home', 24.99);
insert into products (product_id, category, price) values (88, 'Fitness', 12.99);
insert into products (product_id, category, price) values (89, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (90, 'Food - Breakfast', 5.49);
insert into products (product_id, category, price) values (91, 'Food - Vegetables', 4.99);
insert into products (product_id, category, price) values (92, 'Footwear', 29.99);
insert into products (product_id, category, price) values (93, 'Food - Produce', 3.49);
insert into products (product_id, category, price) values (94, 'Pets', 49.99);
insert into products (product_id, category, price) values (95, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (96, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (97, 'Kitchen', 15.99);
insert into products (product_id, category, price) values (98, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (99, 'Food - Sauces', 3.99);
insert into products (product_id, category, price) values (100, 'Food - Seafood', 6.49);
insert into products (product_id, category, price) values (101, 'Outdoor', 149.99);
insert into products (product_id, category, price) values (102, 'Home', 29.99);
insert into products (product_id, category, price) values (103, 'Food - Pasta', 0.99);
insert into products (product_id, category, price) values (104, 'Office', 5.99);
insert into products (product_id, category, price) values (105, 'Health', 49.99);
insert into products (product_id, category, price) values (106, 'Food - Oils', 8.99);
insert into products (product_id, category, price) values (107, 'Photography', 89.99);
insert into products (product_id, category, price) values (108, 'Food - Baking & Cooking', 2.99);
insert into products (product_id, category, price) values (109, 'Toys', 10.99);
insert into products (product_id, category, price) values (110, 'Food - Bakery', 3.49);
insert into products (product_id, category, price) values (111, 'Food - Prepared Meals', 7.49);
insert into products (product_id, category, price) values (112, 'Food - Baking', 5.49);
insert into products (product_id, category, price) values (113, 'Toys', 24.99);
insert into products (product_id, category, price) values (114, 'Food - Frozen Desserts', 6.99);
insert into products (product_id, category, price) values (115, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (116, 'Clothing', 14.99);
insert into products (product_id, category, price) values (117, 'Food - Canned Goods', 1.29);
insert into products (product_id, category, price) values (118, 'Pets', 14.99);
insert into products (product_id, category, price) values (119, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (120, 'Food - Snacks', 2.29);
insert into products (product_id, category, price) values (121, 'Food - Bakery', 3.99);
insert into products (product_id, category, price) values (122, 'Toys', 19.99);
insert into products (product_id, category, price) values (123, 'Food - Nuts', 8.99);
insert into products (product_id, category, price) values (124, 'Clothing - Footwear', 79.99);
insert into products (product_id, category, price) values (125, 'Food - Snacks', 12.99);
insert into products (product_id, category, price) values (126, 'Fitness', 25.99);
insert into products (product_id, category, price) values (127, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (128, 'Kitchen', 59.99);
insert into products (product_id, category, price) values (129, 'Smart Home', 19.99);
insert into products (product_id, category, price) values (130, 'Food - Salads', 5.99);
insert into products (product_id, category, price) values (131, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (132, 'Food - Bakery', 3.79);
insert into products (product_id, category, price) values (133, 'Clothing - Tops', 19.99);
insert into products (product_id, category, price) values (134, 'Outdoor', 69.99);
insert into products (product_id, category, price) values (135, 'Electronics', 99.99);
insert into products (product_id, category, price) values (136, 'Food - Vegetables', 1.29);
insert into products (product_id, category, price) values (137, 'Food - Produce', 2.99);
insert into products (product_id, category, price) values (138, 'Outdoor', 39.99);
insert into products (product_id, category, price) values (139, 'Home', 29.99);
insert into products (product_id, category, price) values (140, 'Home', 19.99);
insert into products (product_id, category, price) values (141, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (142, 'Food - Frozen Foods', 7.99);
insert into products (product_id, category, price) values (143, 'Food - Frozen Foods', 8.99);
insert into products (product_id, category, price) values (144, 'Food - Frozen Meals', 8.99);
insert into products (product_id, category, price) values (145, 'Home Appliances', 299.99);
insert into products (product_id, category, price) values (146, 'Food - Baking Goods', 4.19);
insert into products (product_id, category, price) values (147, 'Kitchen', 79.99);
insert into products (product_id, category, price) values (148, 'Food - Snacks', 4.29);
insert into products (product_id, category, price) values (149, 'Health', 79.99);
insert into products (product_id, category, price) values (150, 'Food - Baking', 3.49);
insert into products (product_id, category, price) values (151, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (152, 'Storage', 9.99);
insert into products (product_id, category, price) values (153, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (154, 'Accessories', 24.99);
insert into products (product_id, category, price) values (155, 'Food - Bakery', 2.99);
insert into products (product_id, category, price) values (156, 'Electronics', 129.99);
insert into products (product_id, category, price) values (157, 'Food - Fruits', 4.99);
insert into products (product_id, category, price) values (158, 'Food - Canned Goods', 2.49);
insert into products (product_id, category, price) values (159, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (160, 'Kitchen', 59.99);
insert into products (product_id, category, price) values (161, 'Food - Salads', 4.29);
insert into products (product_id, category, price) values (162, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (163, 'Electronics', 249.99);
insert into products (product_id, category, price) values (164, 'Home Appliances', 199.99);
insert into products (product_id, category, price) values (165, 'Food - Produce', 3.99);
insert into products (product_id, category, price) values (166, 'Art Supplies', 29.99);
insert into products (product_id, category, price) values (167, 'Clothing - Bottoms', 44.99);
insert into products (product_id, category, price) values (168, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (169, 'Food - Canned Goods', 4.5);
insert into products (product_id, category, price) values (170, 'Food - Prepared Foods', 4.29);
insert into products (product_id, category, price) values (171, 'Food - Dressings', 2.69);
insert into products (product_id, category, price) values (172, 'Food - Nuts', 2.99);
insert into products (product_id, category, price) values (173, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (174, 'Toys', 39.99);
insert into products (product_id, category, price) values (175, 'Food - Deli Meats', 5.49);
insert into products (product_id, category, price) values (176, 'Food - Condiments', 1.99);
insert into products (product_id, category, price) values (177, 'Food - Condiments', 4.49);
insert into products (product_id, category, price) values (178, 'Accessories', 24.99);
insert into products (product_id, category, price) values (179, 'Clothing - Accessories', 24.99);
insert into products (product_id, category, price) values (180, 'Food - Condiments', 3.79);
insert into products (product_id, category, price) values (181, 'Kitchen', 11.99);
insert into products (product_id, category, price) values (182, 'Health', 29.99);
insert into products (product_id, category, price) values (183, 'Fitness', 15.99);
insert into products (product_id, category, price) values (184, 'Pets', 39.99);
insert into products (product_id, category, price) values (185, 'Home', 12.99);
insert into products (product_id, category, price) values (186, 'Pets', 10.99);
insert into products (product_id, category, price) values (187, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (188, 'Pets', 39.99);
insert into products (product_id, category, price) values (189, 'Travel', 15.99);
insert into products (product_id, category, price) values (190, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (191, 'Automotive', 14.99);
insert into products (product_id, category, price) values (192, 'Office', 99.99);
insert into products (product_id, category, price) values (193, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (194, 'Kitchen', 15.99);
insert into products (product_id, category, price) values (195, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (196, 'Fitness', 39.99);
insert into products (product_id, category, price) values (197, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (198, 'Garden', 22.99);
insert into products (product_id, category, price) values (199, 'Food - Prepared Meals', 5.49);
insert into products (product_id, category, price) values (200, 'Travel', 15.99);
insert into products (product_id, category, price) values (201, 'Food - Spreads', 4.29);
insert into products (product_id, category, price) values (202, 'Food - Snacks', 5.99);
insert into products (product_id, category, price) values (203, 'Apps', 24.99);
insert into products (product_id, category, price) values (204, 'Home', 19.99);
insert into products (product_id, category, price) values (205, 'Food - Sauces', 1.29);
insert into products (product_id, category, price) values (206, 'Footwear', 89.99);
insert into products (product_id, category, price) values (207, 'Kitchen', 12.99);
insert into products (product_id, category, price) values (208, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (209, 'Toys', 29.99);
insert into products (product_id, category, price) values (210, 'Food - Frozen', 2.29);
insert into products (product_id, category, price) values (211, 'Health', 49.99);
insert into products (product_id, category, price) values (212, 'Food - Prepared Foods', 8.99);
insert into products (product_id, category, price) values (213, 'Photography', 89.99);
insert into products (product_id, category, price) values (214, 'Food - Produce', 4.49);
insert into products (product_id, category, price) values (215, 'Food - Prepared Foods', 5.99);
insert into products (product_id, category, price) values (216, 'Photography', 29.99);
insert into products (product_id, category, price) values (217, 'Food - Prepared Foods', 6.49);
insert into products (product_id, category, price) values (218, 'Food - Snacks', 3.5);
insert into products (product_id, category, price) values (219, 'Food - Snacks', 4.29);
insert into products (product_id, category, price) values (220, 'Food - Snacks', 2.29);
insert into products (product_id, category, price) values (221, 'Automotive', 19.99);
insert into products (product_id, category, price) values (222, 'Fitness', 15.99);
insert into products (product_id, category, price) values (223, 'Food - Bakery', 5.49);
insert into products (product_id, category, price) values (224, 'Food - Baking & Cooking', 4.99);
insert into products (product_id, category, price) values (225, 'Food - Frozen Foods', 3.69);
insert into products (product_id, category, price) values (226, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (227, 'Accessories', 19.99);
insert into products (product_id, category, price) values (228, 'Outdoor', 27.99);
insert into products (product_id, category, price) values (229, 'Kitchen', 9.99);
insert into products (product_id, category, price) values (230, 'Food - Grab-and-Go', 5.99);
insert into products (product_id, category, price) values (231, 'Food - Condiments', 6.49);
insert into products (product_id, category, price) values (232, 'Fitness', 12.99);
insert into products (product_id, category, price) values (233, 'Clothing - Pants', 54.99);
insert into products (product_id, category, price) values (234, 'Fitness', 34.99);
insert into products (product_id, category, price) values (235, 'Clothing - Dresses', 69.99);
insert into products (product_id, category, price) values (236, 'Food - Prepared Foods', 3.99);
insert into products (product_id, category, price) values (237, 'Home', 24.99);
insert into products (product_id, category, price) values (238, 'Beauty', 99.99);
insert into products (product_id, category, price) values (239, 'Office', 39.99);
insert into products (product_id, category, price) values (240, 'Food - Frozen Meals', 5.99);
insert into products (product_id, category, price) values (241, 'Food - Pasta', 6.49);
insert into products (product_id, category, price) values (242, 'Food - Nuts', 4.29);
insert into products (product_id, category, price) values (243, 'Health', 49.95);
insert into products (product_id, category, price) values (244, 'Food - Household', 12.99);
insert into products (product_id, category, price) values (245, 'Electronics', 19.99);
insert into products (product_id, category, price) values (246, 'Office', 19.99);
insert into products (product_id, category, price) values (247, 'Food - Grains', 4.49);
insert into products (product_id, category, price) values (248, 'Food - Dairy', 3.29);
insert into products (product_id, category, price) values (249, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (250, 'Toys', 29.99);
insert into products (product_id, category, price) values (251, 'Fitness', 18.99);
insert into products (product_id, category, price) values (252, 'Food - Canned Goods', 4.5);
insert into products (product_id, category, price) values (253, 'Garden', 34.99);
insert into products (product_id, category, price) values (254, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (255, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (256, 'Home Improvement', 199.99);
insert into products (product_id, category, price) values (257, 'Art Supplies', 25.99);
insert into products (product_id, category, price) values (258, 'Accessories', 19.99);
insert into products (product_id, category, price) values (259, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (260, 'Accessories', 24.99);
insert into products (product_id, category, price) values (261, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (262, 'Home', 29.99);
insert into products (product_id, category, price) values (263, 'Pets', 59.99);
insert into products (product_id, category, price) values (264, 'Food - Spices', 2.99);
insert into products (product_id, category, price) values (265, 'Office', 29.99);
insert into products (product_id, category, price) values (266, 'Electronics', 49.99);
insert into products (product_id, category, price) values (267, 'Food - Meat', 8.99);
insert into products (product_id, category, price) values (268, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (269, 'Food - Dairy', 3.49);
insert into products (product_id, category, price) values (270, 'Food - Vegetables', 3.99);
insert into products (product_id, category, price) values (271, 'Food - Canned Goods', 2.29);
insert into products (product_id, category, price) values (272, 'Food - Canned Goods', 7.99);
insert into products (product_id, category, price) values (273, 'Food - Grains', 2.99);
insert into products (product_id, category, price) values (274, 'Food - Frozen', 2.49);
insert into products (product_id, category, price) values (275, 'Home', 15.99);
insert into products (product_id, category, price) values (276, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (277, 'Garden', 39.99);
insert into products (product_id, category, price) values (278, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (279, 'Food - Baking', 3.29);
insert into products (product_id, category, price) values (280, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (281, 'Electronics', 129.99);
insert into products (product_id, category, price) values (282, 'Food - Sauces', 4.79);
insert into products (product_id, category, price) values (283, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (284, 'Audio', 59.99);
insert into products (product_id, category, price) values (285, 'Food - Pasta', 2.89);
insert into products (product_id, category, price) values (286, 'Health', 14.99);
insert into products (product_id, category, price) values (287, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (288, 'Food - Nuts', 8.49);
insert into products (product_id, category, price) values (289, 'Toys', 19.99);
insert into products (product_id, category, price) values (290, 'Pets', 9.99);
insert into products (product_id, category, price) values (291, 'Food - Desserts', 2.99);
insert into products (product_id, category, price) values (292, 'Home', 24.99);
insert into products (product_id, category, price) values (293, 'Home', 12.99);
insert into products (product_id, category, price) values (294, 'Food - Canned Goods', 2.49);
insert into products (product_id, category, price) values (295, 'Clothing - Loungewear', 59.99);
insert into products (product_id, category, price) values (296, 'Food - Cooking Kits', 9.99);
insert into products (product_id, category, price) values (297, 'Food - Grains', 3.59);
insert into products (product_id, category, price) values (298, 'Food - Dairy', 3.29);
insert into products (product_id, category, price) values (299, 'Storage', 9.99);
insert into products (product_id, category, price) values (300, 'Clothing - Dresses', 49.99);
insert into products (product_id, category, price) values (301, 'Food - Confectionery', 4.99);
insert into products (product_id, category, price) values (302, 'Food - Frozen', 6.49);
insert into products (product_id, category, price) values (303, 'Garden', 15.99);
insert into products (product_id, category, price) values (304, 'Outdoor', 129.99);
insert into products (product_id, category, price) values (305, 'Apps', 24.99);
insert into products (product_id, category, price) values (306, 'Toys', 29.99);
insert into products (product_id, category, price) values (307, 'Food - Sauces', 4.99);
insert into products (product_id, category, price) values (308, 'Food - Soups', 2.99);
insert into products (product_id, category, price) values (309, 'Food - Condiments', 3.59);
insert into products (product_id, category, price) values (310, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (311, 'Electronics', 49.99);
insert into products (product_id, category, price) values (312, 'Garden', 19.99);
insert into products (product_id, category, price) values (313, 'Accessories', 19.99);
insert into products (product_id, category, price) values (314, 'Food - Beverages', 3.29);
insert into products (product_id, category, price) values (315, 'Food - Condiments', 4.49);
insert into products (product_id, category, price) values (316, 'Outdoor', 69.99);
insert into products (product_id, category, price) values (317, 'Food - Canned Goods', 2.49);
insert into products (product_id, category, price) values (318, 'Food - Condiments', 3.99);
insert into products (product_id, category, price) values (319, 'Food - Desserts', 2.99);
insert into products (product_id, category, price) values (320, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (321, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (322, 'Food - Prepared Foods', 4.29);
insert into products (product_id, category, price) values (323, 'Food - Beverages', 3.29);
insert into products (product_id, category, price) values (324, 'Crafts', 22.99);
insert into products (product_id, category, price) values (325, 'Accessories', 19.99);
insert into products (product_id, category, price) values (326, 'Fitness', 39.99);
insert into products (product_id, category, price) values (327, 'Food - Prepared Meals', 5.99);
insert into products (product_id, category, price) values (328, 'Food - Grains', 3.59);
insert into products (product_id, category, price) values (329, 'Audio', 39.99);
insert into products (product_id, category, price) values (330, 'Pets', 26.99);
insert into products (product_id, category, price) values (331, 'Food - Canned Goods', 2.49);
insert into products (product_id, category, price) values (332, 'Pets', 109.99);
insert into products (product_id, category, price) values (333, 'Clothing - Accessories', 19.99);
insert into products (product_id, category, price) values (334, 'Food - Condiments', 3.79);
insert into products (product_id, category, price) values (335, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (336, 'Outdoor', 39.99);
insert into products (product_id, category, price) values (337, 'Food - Frozen Foods', 4.29);
insert into products (product_id, category, price) values (338, 'Fitness', 15.99);
insert into products (product_id, category, price) values (339, 'Fitness', 39.99);
insert into products (product_id, category, price) values (340, 'Audio', 49.99);
insert into products (product_id, category, price) values (341, 'Electronics', 45.99);
insert into products (product_id, category, price) values (342, 'Food - Frozen Foods', 5.99);
insert into products (product_id, category, price) values (343, 'Health', 59.99);
insert into products (product_id, category, price) values (344, 'Clothing - Shirts', 29.99);
insert into products (product_id, category, price) values (345, 'Food - Baking & Cooking', 4.99);
insert into products (product_id, category, price) values (346, 'Food - Condiments', 3.99);
insert into products (product_id, category, price) values (347, 'Food - Spices', 2.99);
insert into products (product_id, category, price) values (348, 'Food - Grains', 2.99);
insert into products (product_id, category, price) values (349, 'Fitness', 12.99);
insert into products (product_id, category, price) values (350, 'Food - Frozen Foods', 5.49);
insert into products (product_id, category, price) values (351, 'Accessories', 12.99);
insert into products (product_id, category, price) values (352, 'Food - Beverages', 5.99);
insert into products (product_id, category, price) values (353, 'Clothing - Swimwear', 29.99);
insert into products (product_id, category, price) values (354, 'Home Appliances', 199.99);
insert into products (product_id, category, price) values (355, 'Electronics', 39.99);
insert into products (product_id, category, price) values (356, 'Food - Pasta', 4.19);
insert into products (product_id, category, price) values (357, 'Toys', 24.99);
insert into products (product_id, category, price) values (358, 'Home Improvement', 39.99);
insert into products (product_id, category, price) values (359, 'Books', 29.99);
insert into products (product_id, category, price) values (360, 'Food - Grains', 2.29);
insert into products (product_id, category, price) values (361, 'Food - Snacks', 5.49);
insert into products (product_id, category, price) values (362, 'Food - Sauces', 3.59);
insert into products (product_id, category, price) values (363, 'Toys', 34.99);
insert into products (product_id, category, price) values (364, 'Automotive', 49.99);
insert into products (product_id, category, price) values (365, 'Food - Frozen Meals', 5.99);
insert into products (product_id, category, price) values (366, 'Food - Grains', 2.49);
insert into products (product_id, category, price) values (367, 'Travel', 12.99);
insert into products (product_id, category, price) values (368, 'Food - Prepared Foods', 5.79);
insert into products (product_id, category, price) values (369, 'Food - Prepared Meals', 4.49);
insert into products (product_id, category, price) values (370, 'Garden', 22.99);
insert into products (product_id, category, price) values (371, 'Food - Vegetables', 1.29);
insert into products (product_id, category, price) values (372, 'Fitness', 12.99);
insert into products (product_id, category, price) values (373, 'Garden', 22.99);
insert into products (product_id, category, price) values (374, 'Food - Produce', 2.99);
insert into products (product_id, category, price) values (375, 'Pets', 19.99);
insert into products (product_id, category, price) values (376, 'Food - Grains', 2.49);
insert into products (product_id, category, price) values (377, 'Pets', 149.99);
insert into products (product_id, category, price) values (378, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (379, 'Food - Seafood', 4.19);
insert into products (product_id, category, price) values (380, 'Home', 24.99);
insert into products (product_id, category, price) values (381, 'Clothing - Footwear', 69.99);
insert into products (product_id, category, price) values (382, 'Music', 39.99);
insert into products (product_id, category, price) values (383, 'Food - Breakfast', 4.99);
insert into products (product_id, category, price) values (384, 'Food - Baking', 3.99);
insert into products (product_id, category, price) values (385, 'Fitness', 19.99);
insert into products (product_id, category, price) values (386, 'Food - Fresh Produce', 0.75);
insert into products (product_id, category, price) values (387, 'Food - Beverages', 3.29);
insert into products (product_id, category, price) values (388, 'Food - Spices', 1.99);
insert into products (product_id, category, price) values (389, 'Food - Baking Goods', 1.89);
insert into products (product_id, category, price) values (390, 'Food - Frozen Foods', 3.29);
insert into products (product_id, category, price) values (391, 'Food - Beverages', 2.49);
insert into products (product_id, category, price) values (392, 'Outdoor', 159.99);
insert into products (product_id, category, price) values (393, 'Food - Bakery', 4.49);
insert into products (product_id, category, price) values (394, 'Food - Snacks', 4.29);
insert into products (product_id, category, price) values (395, 'Kitchen', 18.99);
insert into products (product_id, category, price) values (396, 'Toys', 24.99);
insert into products (product_id, category, price) values (397, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (398, 'Baby', 9.99);
insert into products (product_id, category, price) values (399, 'Food - Canned Goods', 4.5);
insert into products (product_id, category, price) values (400, 'Food - Meat', 6.99);
insert into products (product_id, category, price) values (401, 'Electronics', 34.99);
insert into products (product_id, category, price) values (402, 'Food - Produce', 6.99);
insert into products (product_id, category, price) values (403, 'Home', 17.99);
insert into products (product_id, category, price) values (404, 'Pets', 69.99);
insert into products (product_id, category, price) values (405, 'Garden', 39.99);
insert into products (product_id, category, price) values (406, 'Food - Meat', 8.99);
insert into products (product_id, category, price) values (407, 'Fitness', 29.99);
insert into products (product_id, category, price) values (408, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (409, 'Food - Canned Goods', 2.99);
insert into products (product_id, category, price) values (410, 'Pets', 89.99);
insert into products (product_id, category, price) values (411, 'Accessories', 24.99);
insert into products (product_id, category, price) values (412, 'Photography', 14.99);
insert into products (product_id, category, price) values (413, 'Food - Dairy', 5.99);
insert into products (product_id, category, price) values (414, 'Clothing', 49.99);
insert into products (product_id, category, price) values (415, 'Home', 19.99);
insert into products (product_id, category, price) values (416, 'Food - Meats', 4.99);
insert into products (product_id, category, price) values (417, 'Clothing', 14.99);
insert into products (product_id, category, price) values (418, 'Food - Snacks', 2.29);
insert into products (product_id, category, price) values (419, 'Accessories', 69.99);
insert into products (product_id, category, price) values (420, 'Food - Soups', 2.99);
insert into products (product_id, category, price) values (421, 'Electronics', 99.99);
insert into products (product_id, category, price) values (422, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (423, 'Food - Beverages', 4.29);
insert into products (product_id, category, price) values (424, 'Food - Breakfast', 2.49);
insert into products (product_id, category, price) values (425, 'Food - Condiments', 2.49);
insert into products (product_id, category, price) values (426, 'Pets', 9.99);
insert into products (product_id, category, price) values (427, 'Electronics', 29.99);
insert into products (product_id, category, price) values (428, 'Health', 19.99);
insert into products (product_id, category, price) values (429, 'Food - Condiments', 3.59);
insert into products (product_id, category, price) values (430, 'Clothing', 49.99);
insert into products (product_id, category, price) values (431, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (432, 'Food - Snacks', 4.29);
insert into products (product_id, category, price) values (433, 'Accessories', 19.99);
insert into products (product_id, category, price) values (434, 'Home', 22.99);
insert into products (product_id, category, price) values (435, 'Food - Frozen Desserts', 4.99);
insert into products (product_id, category, price) values (436, 'Home Appliances', 299.99);
insert into products (product_id, category, price) values (437, 'Food - Baking', 5.59);
insert into products (product_id, category, price) values (438, 'Clothing', 49.99);
insert into products (product_id, category, price) values (439, 'Electronics', 12.99);
insert into products (product_id, category, price) values (440, 'Travel', 15.99);
insert into products (product_id, category, price) values (441, 'Kitchen', 199.99);
insert into products (product_id, category, price) values (442, 'Crafts', 34.99);
insert into products (product_id, category, price) values (443, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (444, 'Automotive', 59.99);
insert into products (product_id, category, price) values (445, 'Outdoor', 22.99);
insert into products (product_id, category, price) values (446, 'Accessories', 12.99);
insert into products (product_id, category, price) values (447, 'Health', 89.99);
insert into products (product_id, category, price) values (448, 'Home', 24.99);
insert into products (product_id, category, price) values (449, 'Food - Frozen Desserts', 4.5);
insert into products (product_id, category, price) values (450, 'Fitness', 25.99);
insert into products (product_id, category, price) values (451, 'Food - Dairy', 3.29);
insert into products (product_id, category, price) values (452, 'Food - Canned Goods', 2.49);
insert into products (product_id, category, price) values (453, 'Kitchen', 18.99);
insert into products (product_id, category, price) values (454, 'Health', 34.99);
insert into products (product_id, category, price) values (455, 'Toys', 19.99);
insert into products (product_id, category, price) values (456, 'Food - Meat', 12.99);
insert into products (product_id, category, price) values (457, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (458, 'Food - Produce', 4.29);
insert into products (product_id, category, price) values (459, 'Food - Baking', 4.89);
insert into products (product_id, category, price) values (460, 'Kitchen', 34.99);
insert into products (product_id, category, price) values (461, 'Outdoor', 99.99);
insert into products (product_id, category, price) values (462, 'Food - Produce', 2.99);
insert into products (product_id, category, price) values (463, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (464, 'Food - Seafood', 12.99);
insert into products (product_id, category, price) values (465, 'Accessories', 12.99);
insert into products (product_id, category, price) values (466, 'Baby', 39.99);
insert into products (product_id, category, price) values (467, 'Crafts', 34.99);
insert into products (product_id, category, price) values (468, 'Tools', 29.99);
insert into products (product_id, category, price) values (469, 'Fitness', 19.99);
insert into products (product_id, category, price) values (470, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (471, 'Food - Snacks', 4.99);
insert into products (product_id, category, price) values (472, 'Food - Frozen Meals', 6.49);
insert into products (product_id, category, price) values (473, 'Toys', 19.99);
insert into products (product_id, category, price) values (474, 'Art Supplies', 18.99);
insert into products (product_id, category, price) values (475, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (476, 'Food - Dairy Alternatives', 1.99);
insert into products (product_id, category, price) values (477, 'Safety', 99.99);
insert into products (product_id, category, price) values (478, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (479, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (480, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (481, 'Food - Snacks', 4.49);
insert into products (product_id, category, price) values (482, 'Food - Meat', 9.99);
insert into products (product_id, category, price) values (483, 'Garden', 49.99);
insert into products (product_id, category, price) values (484, 'Food - Oils', 8.99);
insert into products (product_id, category, price) values (485, 'Food - Prepared Meals', 8.99);
insert into products (product_id, category, price) values (486, 'Food - Condiments', 5.29);
insert into products (product_id, category, price) values (487, 'Fitness', 22.99);
insert into products (product_id, category, price) values (488, 'Home', 19.99);
insert into products (product_id, category, price) values (489, 'Food - Condiments', 3.99);
insert into products (product_id, category, price) values (490, 'Food - Beverages', 5.99);
insert into products (product_id, category, price) values (491, 'Office', 99.99);
insert into products (product_id, category, price) values (492, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (493, 'Food - Dairy Alternatives', 1.99);
insert into products (product_id, category, price) values (494, 'Health', 49.99);
insert into products (product_id, category, price) values (495, 'Garden', 32.99);
insert into products (product_id, category, price) values (496, 'Office', 39.99);
insert into products (product_id, category, price) values (497, 'Kitchen', 22.99);
insert into products (product_id, category, price) values (498, 'Food - Breakfast', 2.49);
insert into products (product_id, category, price) values (499, 'Electronics', 12.99);
insert into products (product_id, category, price) values (500, 'Food - Produce', 1.29);
insert into products (product_id, category, price) values (501, 'Home', 29.99);
insert into products (product_id, category, price) values (502, 'Food - Baking', 1.99);
insert into products (product_id, category, price) values (503, 'Food - Frozen', 5.99);
insert into products (product_id, category, price) values (504, 'Food - Frozen', 2.29);
insert into products (product_id, category, price) values (505, 'Outdoor', 109.99);
insert into products (product_id, category, price) values (506, 'Food - Grains', 3.29);
insert into products (product_id, category, price) values (507, 'Clothing - Accessories', 19.99);
insert into products (product_id, category, price) values (508, 'Food - Vegetarian', 5.49);
insert into products (product_id, category, price) values (509, 'Food - Baking', 3.79);
insert into products (product_id, category, price) values (510, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (511, 'Home', 34.99);
insert into products (product_id, category, price) values (512, 'Food - Spices', 2.99);
insert into products (product_id, category, price) values (513, 'Photography', 49.99);
insert into products (product_id, category, price) values (514, 'Electronics', 29.99);
insert into products (product_id, category, price) values (515, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (516, 'Fitness', 34.99);
insert into products (product_id, category, price) values (517, 'Kitchen', 12.99);
insert into products (product_id, category, price) values (518, 'Food - Grocery', 3.99);
insert into products (product_id, category, price) values (519, 'Kitchen', 12.99);
insert into products (product_id, category, price) values (520, 'Accessories', 24.99);
insert into products (product_id, category, price) values (521, 'Health', 59.99);
insert into products (product_id, category, price) values (522, 'Outdoor', 149.99);
insert into products (product_id, category, price) values (523, 'Food - Baking', 4.29);
insert into products (product_id, category, price) values (524, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (525, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (526, 'Food - Canned Goods', 2.99);
insert into products (product_id, category, price) values (527, 'Food - Salads', 3.29);
insert into products (product_id, category, price) values (528, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (529, 'Food - Fresh Produce', 3.99);
insert into products (product_id, category, price) values (530, 'Food - Beverages', 1.99);
insert into products (product_id, category, price) values (531, 'Food - Grocery', 3.99);
insert into products (product_id, category, price) values (532, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (533, 'Fitness', 19.99);
insert into products (product_id, category, price) values (534, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (535, 'Food - Beverages', 2.79);
insert into products (product_id, category, price) values (536, 'Electronics', 49.99);
insert into products (product_id, category, price) values (537, 'Food - Canned Goods', 3.29);
insert into products (product_id, category, price) values (538, 'Food - Grains', 2.49);
insert into products (product_id, category, price) values (539, 'Fitness', 49.99);
insert into products (product_id, category, price) values (540, 'Food - Baking', 6.99);
insert into products (product_id, category, price) values (541, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (542, 'Health', 19.99);
insert into products (product_id, category, price) values (543, 'Food - Vegetables', 3.99);
insert into products (product_id, category, price) values (544, 'Food - Condiments', 4.79);
insert into products (product_id, category, price) values (545, 'Food - Grains', 3.99);
insert into products (product_id, category, price) values (546, 'Food - Spices', 1.99);
insert into products (product_id, category, price) values (547, 'Pets', 19.99);
insert into products (product_id, category, price) values (548, 'Clothing', 49.99);
insert into products (product_id, category, price) values (549, 'Toys', 29.99);
insert into products (product_id, category, price) values (550, 'Baby', 79.99);
insert into products (product_id, category, price) values (551, 'Food - Produce', 6.99);
insert into products (product_id, category, price) values (552, 'Home', 29.99);
insert into products (product_id, category, price) values (553, 'Clothing - Bottoms', 44.99);
insert into products (product_id, category, price) values (554, 'Food - Supplements', 24.99);
insert into products (product_id, category, price) values (555, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (556, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (557, 'Food - Frozen Foods', 4.29);
insert into products (product_id, category, price) values (558, 'Art Supplies', 25.99);
insert into products (product_id, category, price) values (559, 'Fitness', 14.99);
insert into products (product_id, category, price) values (560, 'Food - Condiments', 5.29);
insert into products (product_id, category, price) values (561, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (562, 'Smart Home', 19.99);
insert into products (product_id, category, price) values (563, 'Office', 39.99);
insert into products (product_id, category, price) values (564, 'Gaming', 299.99);
insert into products (product_id, category, price) values (565, 'Clothing - Activewear', 39.99);
insert into products (product_id, category, price) values (566, 'Fitness', 25);
insert into products (product_id, category, price) values (567, 'Food - Desserts', 4.99);
insert into products (product_id, category, price) values (568, 'Food - Breakfast', 2.99);
insert into products (product_id, category, price) values (569, 'Home', 22.99);
insert into products (product_id, category, price) values (570, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (571, 'Food - Condiments', 5.29);
insert into products (product_id, category, price) values (572, 'Food - Nuts', 10.99);
insert into products (product_id, category, price) values (573, 'Clothing', 64.99);
insert into products (product_id, category, price) values (574, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (575, 'Food - Cereals', 3.79);
insert into products (product_id, category, price) values (576, 'Home Appliances', 299.99);
insert into products (product_id, category, price) values (577, 'Electronics', 199.99);
insert into products (product_id, category, price) values (578, 'Food - Produce', 3.99);
insert into products (product_id, category, price) values (579, 'Food - Condiments', 5.29);
insert into products (product_id, category, price) values (580, 'Clothing - Footwear', 24.99);
insert into products (product_id, category, price) values (581, 'Food - Frozen Foods', 5.99);
insert into products (product_id, category, price) values (582, 'Food - Grains', 6.99);
insert into products (product_id, category, price) values (583, 'Home', 69.99);
insert into products (product_id, category, price) values (584, 'Kitchen', 12.99);
insert into products (product_id, category, price) values (585, 'Food - Canned Goods', 7.99);
insert into products (product_id, category, price) values (586, 'Food - Canned Goods', 1.69);
insert into products (product_id, category, price) values (587, 'Kitchen', 89.99);
insert into products (product_id, category, price) values (588, 'Food - Cereal', 3.49);
insert into products (product_id, category, price) values (589, 'Food - Beverages', 2.49);
insert into products (product_id, category, price) values (590, 'Automotive', 15.99);
insert into products (product_id, category, price) values (591, 'Health', 19.99);
insert into products (product_id, category, price) values (592, 'Crafts', 34.99);
insert into products (product_id, category, price) values (593, 'Food - Prepared Meals', 5.99);
insert into products (product_id, category, price) values (594, 'Food - Meat', 7.99);
insert into products (product_id, category, price) values (595, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (596, 'Food - Breakfast', 5.49);
insert into products (product_id, category, price) values (597, 'Food - Bread', 2.79);
insert into products (product_id, category, price) values (598, 'Food - Salads', 3.99);
insert into products (product_id, category, price) values (599, 'Food - Prepared Foods', 5.49);
insert into products (product_id, category, price) values (600, 'Health', 20.99);
insert into products (product_id, category, price) values (601, 'Toys', 29.99);
insert into products (product_id, category, price) values (602, 'Baby', 79.99);
insert into products (product_id, category, price) values (603, 'Food - Frozen Foods', 5.49);
insert into products (product_id, category, price) values (604, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (605, 'Food - Grains', 2.49);
insert into products (product_id, category, price) values (606, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (607, 'Food - Condiments', 4.29);
insert into products (product_id, category, price) values (608, 'Pets', 109.99);
insert into products (product_id, category, price) values (609, 'Automotive', 44.99);
insert into products (product_id, category, price) values (610, 'Food - Produce', 4.49);
insert into products (product_id, category, price) values (611, 'Fitness', 29.99);
insert into products (product_id, category, price) values (612, 'Food - Nuts', 7.99);
insert into products (product_id, category, price) values (613, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (614, 'Food - Dairy', 3.99);
insert into products (product_id, category, price) values (615, 'Food - Frozen', 1.99);
insert into products (product_id, category, price) values (616, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (617, 'Electronics', 29.99);
insert into products (product_id, category, price) values (618, 'Office', 5.99);
insert into products (product_id, category, price) values (619, 'Food - Meat & Seafood', 4.99);
insert into products (product_id, category, price) values (620, 'Beauty', 25.99);
insert into products (product_id, category, price) values (621, 'Pets', 14.99);
insert into products (product_id, category, price) values (622, 'Computers', 99.99);
insert into products (product_id, category, price) values (623, 'Food - Frozen Foods', 3.99);
insert into products (product_id, category, price) values (624, 'Garden', 22.99);
insert into products (product_id, category, price) values (625, 'Food', 29.99);
insert into products (product_id, category, price) values (626, 'Home', 39.99);
insert into products (product_id, category, price) values (627, 'Accessories', 24.99);
insert into products (product_id, category, price) values (628, 'Food - Frozen', 5.99);
insert into products (product_id, category, price) values (629, 'Toys', 29.99);
insert into products (product_id, category, price) values (630, 'Pets', 15.99);
insert into products (product_id, category, price) values (631, 'Music', 19.99);
insert into products (product_id, category, price) values (632, 'Health', 79.99);
insert into products (product_id, category, price) values (633, 'Fitness', 12.99);
insert into products (product_id, category, price) values (634, 'Food - Desserts', 2.99);
insert into products (product_id, category, price) values (635, 'Food - Condiments', 3.49);
insert into products (product_id, category, price) values (636, 'Home', 19.99);
insert into products (product_id, category, price) values (637, 'Pets', 39.99);
insert into products (product_id, category, price) values (638, 'Pets', 69.99);
insert into products (product_id, category, price) values (639, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (640, 'Food - Snacks', 5.49);
insert into products (product_id, category, price) values (641, 'Food - Bakery', 2.99);
insert into products (product_id, category, price) values (642, 'Clothing', 29.99);
insert into products (product_id, category, price) values (643, 'Food - Desserts', 6.29);
insert into products (product_id, category, price) values (644, 'Clothing', 44.99);
insert into products (product_id, category, price) values (645, 'Automotive', 44.99);
insert into products (product_id, category, price) values (646, 'Accessories', 19.99);
insert into products (product_id, category, price) values (647, 'Music', 39.99);
insert into products (product_id, category, price) values (648, 'Fitness', 14.99);
insert into products (product_id, category, price) values (649, 'Garden', 19.99);
insert into products (product_id, category, price) values (650, 'Food - Frozen Food', 5.99);
insert into products (product_id, category, price) values (651, 'Outdoor', 59.99);
insert into products (product_id, category, price) values (652, 'Travel', 24.99);
insert into products (product_id, category, price) values (653, 'Food - Beverages', 1.99);
insert into products (product_id, category, price) values (654, 'Home', 16.99);
insert into products (product_id, category, price) values (655, 'Kitchen', 34.99);
insert into products (product_id, category, price) values (656, 'Food - Produce', 3.49);
insert into products (product_id, category, price) values (657, 'Food - Condiments', 4.09);
insert into products (product_id, category, price) values (658, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (659, 'Accessories', 24.99);
insert into products (product_id, category, price) values (660, 'Health', 39.99);
insert into products (product_id, category, price) values (661, 'Clothing', 44.99);
insert into products (product_id, category, price) values (662, 'Health', 79.99);
insert into products (product_id, category, price) values (663, 'Toys', 22.99);
insert into products (product_id, category, price) values (664, 'Art Supplies', 24.99);
insert into products (product_id, category, price) values (665, 'Food - Snacks', 3.59);
insert into products (product_id, category, price) values (666, 'Books', 19.99);
insert into products (product_id, category, price) values (667, 'Food - Condiments', 5.49);
insert into products (product_id, category, price) values (668, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (669, 'Crafts', 22.99);
insert into products (product_id, category, price) values (670, 'Gaming', 89.99);
insert into products (product_id, category, price) values (671, 'Food - Snacks', 4.99);
insert into products (product_id, category, price) values (672, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (673, 'Food - Produce', 3.49);
insert into products (product_id, category, price) values (674, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (675, 'Food - Prepared Foods', 4.99);
insert into products (product_id, category, price) values (676, 'Food - Beverages', 2.99);
insert into products (product_id, category, price) values (677, 'Outdoor', 79.99);
insert into products (product_id, category, price) values (678, 'Outdoor', 9.99);
insert into products (product_id, category, price) values (679, 'Food - Canned Goods', 3.99);
insert into products (product_id, category, price) values (680, 'Home', 29.99);
insert into products (product_id, category, price) values (681, 'Food - Deli', 2.99);
insert into products (product_id, category, price) values (682, 'Food - Snacks', 1.99);
insert into products (product_id, category, price) values (683, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (684, 'Food - Frozen', 1.99);
insert into products (product_id, category, price) values (685, 'Food - Condiments', 4.29);
insert into products (product_id, category, price) values (686, 'Food - Meat & Seafood', 4.99);
insert into products (product_id, category, price) values (687, 'Food - Beverages', 4.49);
insert into products (product_id, category, price) values (688, 'Food - Breakfast', 4.29);
insert into products (product_id, category, price) values (689, 'Crafts', 22.99);
insert into products (product_id, category, price) values (690, 'Fitness', 25.99);
insert into products (product_id, category, price) values (691, 'Food - Snacks', 5.29);
insert into products (product_id, category, price) values (692, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (693, 'Photography', 29.99);
insert into products (product_id, category, price) values (694, 'Food - Prepared Foods', 3.99);
insert into products (product_id, category, price) values (695, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (696, 'Food - Meat', 5.99);
insert into products (product_id, category, price) values (697, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (698, 'Furniture', 199.99);
insert into products (product_id, category, price) values (699, 'Food - Grains', 2.99);
insert into products (product_id, category, price) values (700, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (701, 'Food - Frozen', 7.49);
insert into products (product_id, category, price) values (702, 'Food - Prepared Foods', 5.99);
insert into products (product_id, category, price) values (703, 'Pets', 69.99);
insert into products (product_id, category, price) values (704, 'Food - Soups', 3.49);
insert into products (product_id, category, price) values (705, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (706, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (707, 'Outdoor', 59.99);
insert into products (product_id, category, price) values (708, 'Food - Snacks', 3.99);
insert into products (product_id, category, price) values (709, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (710, 'Food - Canned Goods', 2.99);
insert into products (product_id, category, price) values (711, 'Food - Nuts', 8.99);
insert into products (product_id, category, price) values (712, 'Automotive', 49.99);
insert into products (product_id, category, price) values (713, 'Food - Sides', 3.99);
insert into products (product_id, category, price) values (714, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (715, 'Food - Canned Goods', 2.99);
insert into products (product_id, category, price) values (716, 'Food - Beverages', 1.99);
insert into products (product_id, category, price) values (717, 'Automotive', 12.99);
insert into products (product_id, category, price) values (718, 'Food - Breakfast', 4.99);
insert into products (product_id, category, price) values (719, 'Toys', 22.99);
insert into products (product_id, category, price) values (720, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (721, 'Accessories', 99.99);
insert into products (product_id, category, price) values (722, 'Audio', 24.99);
insert into products (product_id, category, price) values (723, 'Home', 34.99);
insert into products (product_id, category, price) values (724, 'Food - Baking Goods', 3.99);
insert into products (product_id, category, price) values (725, 'Food - Canned Goods', 1.5);
insert into products (product_id, category, price) values (726, 'Food - Prepared Foods', 5.49);
insert into products (product_id, category, price) values (727, 'Kitchen', 14.99);
insert into products (product_id, category, price) values (728, 'Smart Home', 149.99);
insert into products (product_id, category, price) values (729, 'Tools', 29.99);
insert into products (product_id, category, price) values (730, 'Home', 25.99);
insert into products (product_id, category, price) values (731, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (732, 'Food - Canned Goods', 3.99);
insert into products (product_id, category, price) values (733, 'Health', 34.99);
insert into products (product_id, category, price) values (734, 'Fitness', 12.99);
insert into products (product_id, category, price) values (735, 'Food - Baking', 5.99);
insert into products (product_id, category, price) values (736, 'Home', 29.99);
insert into products (product_id, category, price) values (737, 'Food - Meat', 15.99);
insert into products (product_id, category, price) values (738, 'Fitness', 22.99);
insert into products (product_id, category, price) values (739, 'Fitness', 199.99);
insert into products (product_id, category, price) values (740, 'Art Supplies', 14.99);
insert into products (product_id, category, price) values (741, 'Food - Nuts', 8.99);
insert into products (product_id, category, price) values (742, 'Food - Bakery', 3.99);
insert into products (product_id, category, price) values (743, 'Home', 69.99);
insert into products (product_id, category, price) values (744, 'Office', 99.99);
insert into products (product_id, category, price) values (745, 'Food - Beverages', 3.29);
insert into products (product_id, category, price) values (746, 'Outdoor', 22.99);
insert into products (product_id, category, price) values (747, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (748, 'Baby', 39.99);
insert into products (product_id, category, price) values (749, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (750, 'Toys', 22.99);
insert into products (product_id, category, price) values (751, 'Music', 39.99);
insert into products (product_id, category, price) values (752, 'Food - Soups', 4.99);
insert into products (product_id, category, price) values (753, 'Health', 49.99);
insert into products (product_id, category, price) values (754, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (755, 'Food - Snacks', 3.5);
insert into products (product_id, category, price) values (756, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (757, 'Food - Bakery', 4.49);
insert into products (product_id, category, price) values (758, 'Food - Frozen Foods', 2.99);
insert into products (product_id, category, price) values (759, 'Kitchen', 22.99);
insert into products (product_id, category, price) values (760, 'Travel', 29.99);
insert into products (product_id, category, price) values (761, 'Accessories', 19.99);
insert into products (product_id, category, price) values (762, 'Electronics', 39.99);
insert into products (product_id, category, price) values (763, 'Outdoor', 59.99);
insert into products (product_id, category, price) values (764, 'Toys', 29.99);
insert into products (product_id, category, price) values (765, 'Pets', 14.99);
insert into products (product_id, category, price) values (766, 'Accessories', 19.99);
insert into products (product_id, category, price) values (767, 'Food - Meat', 5.99);
insert into products (product_id, category, price) values (768, 'Kitchen', 10.99);
insert into products (product_id, category, price) values (769, 'Food - Condiments', 3.79);
insert into products (product_id, category, price) values (770, 'Clothing - Footwear', 39.99);
insert into products (product_id, category, price) values (771, 'Accessories', 24.99);
insert into products (product_id, category, price) values (772, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (773, 'Accessories', 49.99);
insert into products (product_id, category, price) values (774, 'Food - Condiments', 6.49);
insert into products (product_id, category, price) values (775, 'Food - Frozen Foods', 3.29);
insert into products (product_id, category, price) values (776, 'Food - Beverages', 3.49);
insert into products (product_id, category, price) values (777, 'Books', 39.99);
insert into products (product_id, category, price) values (778, 'Food - Breakfast', 2.49);
insert into products (product_id, category, price) values (779, 'Food - Condiments', 1.99);
insert into products (product_id, category, price) values (780, 'Storage', 9.99);
insert into products (product_id, category, price) values (781, 'Food - Condiments', 4.49);
insert into products (product_id, category, price) values (782, 'Food - Baking', 2.49);
insert into products (product_id, category, price) values (783, 'Food - Sides', 2.99);
insert into products (product_id, category, price) values (784, 'Food - Meat', 8.49);
insert into products (product_id, category, price) values (785, 'Food - Condiments', 3.79);
insert into products (product_id, category, price) values (786, 'Food - Frozen', 8.99);
insert into products (product_id, category, price) values (787, 'Clothing - Pants', 54.99);
insert into products (product_id, category, price) values (788, 'Food - Snacks', 3.79);
insert into products (product_id, category, price) values (789, 'Food - Soups', 3.89);
insert into products (product_id, category, price) values (790, 'Food - Frozen Foods', 2.99);
insert into products (product_id, category, price) values (791, 'Clothing - Outerwear', 49.99);
insert into products (product_id, category, price) values (792, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (793, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (794, 'Home', 34.99);
insert into products (product_id, category, price) values (795, 'Food - Beverages', 4.49);
insert into products (product_id, category, price) values (796, 'Food - Meat', 5.99);
insert into products (product_id, category, price) values (797, 'Pets', 15.99);
insert into products (product_id, category, price) values (798, 'Food - Beverages', 4.99);
insert into products (product_id, category, price) values (799, 'Food - Meat', 8.49);
insert into products (product_id, category, price) values (800, 'Food - Breakfast', 4.99);
insert into products (product_id, category, price) values (801, 'Food - Frozen Food', 6.49);
insert into products (product_id, category, price) values (802, 'Kitchen', 89.99);
insert into products (product_id, category, price) values (803, 'Food - Frozen Meals', 5.99);
insert into products (product_id, category, price) values (804, 'Fitness', 18.99);
insert into products (product_id, category, price) values (805, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (806, 'Food - Condiments', 1.99);
insert into products (product_id, category, price) values (807, 'Food - Beverages', 7.99);
insert into products (product_id, category, price) values (808, 'Clothing - Accessories', 19.99);
insert into products (product_id, category, price) values (809, 'Food - Snacks', 5.49);
insert into products (product_id, category, price) values (810, 'Food', 19.99);
insert into products (product_id, category, price) values (811, 'Beauty', 29.99);
insert into products (product_id, category, price) values (812, 'Food - Snacks', 2.49);
insert into products (product_id, category, price) values (813, 'Food - Meat', 7.99);
insert into products (product_id, category, price) values (814, 'Food - Health Foods', 7.99);
insert into products (product_id, category, price) values (815, 'Food - Dairy', 3.29);
insert into products (product_id, category, price) values (816, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (817, 'Food - Pantry', 3.59);
insert into products (product_id, category, price) values (818, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (819, 'Kitchen', 29.99);
insert into products (product_id, category, price) values (820, 'Food - Frozen Foods', 3.99);
insert into products (product_id, category, price) values (821, 'Food - Grains', 3.99);
insert into products (product_id, category, price) values (822, 'Fitness', 12.99);
insert into products (product_id, category, price) values (823, 'Toys', 19.99);
insert into products (product_id, category, price) values (824, 'Food - Meat', 6.99);
insert into products (product_id, category, price) values (825, 'Food - Bakery', 3.49);
insert into products (product_id, category, price) values (826, 'Fitness', 34.99);
insert into products (product_id, category, price) values (827, 'Fitness', 25);
insert into products (product_id, category, price) values (828, 'Food - Bread', 2.79);
insert into products (product_id, category, price) values (829, 'Food - Marinades', 3.79);
insert into products (product_id, category, price) values (830, 'Food - Spices', 2.99);
insert into products (product_id, category, price) values (831, 'Food - Condiments', 1.99);
insert into products (product_id, category, price) values (832, 'Food - Sauces', 2.59);
insert into products (product_id, category, price) values (833, 'Clothing - Footwear', 39.99);
insert into products (product_id, category, price) values (834, 'Food - Bakery', 4.49);
insert into products (product_id, category, price) values (835, 'Fitness', 34.99);
insert into products (product_id, category, price) values (836, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (837, 'Food - Baking', 3.29);
insert into products (product_id, category, price) values (838, 'Clothing - Tops', 19.99);
insert into products (product_id, category, price) values (839, 'Home', 29.99);
insert into products (product_id, category, price) values (840, 'Accessories', 19.99);
insert into products (product_id, category, price) values (841, 'Accessories', 24.99);
insert into products (product_id, category, price) values (842, 'Food - Sides', 2.99);
insert into products (product_id, category, price) values (843, 'Home', 12.99);
insert into products (product_id, category, price) values (844, 'Fitness', 12.99);
insert into products (product_id, category, price) values (845, 'Food - Baked Goods', 4.99);
insert into products (product_id, category, price) values (846, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (847, 'Food - Meat', 3.99);
insert into products (product_id, category, price) values (848, 'Clothing - Accessories', 29.99);
insert into products (product_id, category, price) values (849, 'Clothing - Outerwear', 59.99);
insert into products (product_id, category, price) values (850, 'Kitchen', 39);
insert into products (product_id, category, price) values (851, 'Food - Condiments', 4.29);
insert into products (product_id, category, price) values (852, 'Travel', 14.99);
insert into products (product_id, category, price) values (853, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (854, 'Food - Meat Substitutes', 5.99);
insert into products (product_id, category, price) values (855, 'Food - Condiments', 2.79);
insert into products (product_id, category, price) values (856, 'Gaming', 199.99);
insert into products (product_id, category, price) values (857, 'Food - Canned Goods', 2.99);
insert into products (product_id, category, price) values (858, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (859, 'Food - Meat', 5.99);
insert into products (product_id, category, price) values (860, 'Outdoor', 34.99);
insert into products (product_id, category, price) values (861, 'Safety', 24.99);
insert into products (product_id, category, price) values (862, 'Food - Frozen Vegetables', 5.99);
insert into products (product_id, category, price) values (863, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (864, 'Food - Spices', 1.99);
insert into products (product_id, category, price) values (865, 'Food - Frozen Desserts', 5.99);
insert into products (product_id, category, price) values (866, 'Pets', 18.99);
insert into products (product_id, category, price) values (867, 'Food - Prepared Foods', 5.99);
insert into products (product_id, category, price) values (868, 'Food - Beverages', 4.99);
insert into products (product_id, category, price) values (869, 'Food - Condiments', 3.29);
insert into products (product_id, category, price) values (870, 'Home', 19.99);
insert into products (product_id, category, price) values (871, 'Home', 29.99);
insert into products (product_id, category, price) values (872, 'Food - Produce', 0.89);
insert into products (product_id, category, price) values (873, 'Food - Snacks', 4.49);
insert into products (product_id, category, price) values (874, 'Food - Dairy', 2.99);
insert into products (product_id, category, price) values (875, 'Electronics', 15.99);
insert into products (product_id, category, price) values (876, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (877, 'Outdoor', 9.99);
insert into products (product_id, category, price) values (878, 'Food - Baking & Cooking', 2.99);
insert into products (product_id, category, price) values (879, 'Electronics', 29.99);
insert into products (product_id, category, price) values (880, 'Food - Dips', 3.29);
insert into products (product_id, category, price) values (881, 'Food - Baking', 1.49);
insert into products (product_id, category, price) values (882, 'Food - Cereal', 2.49);
insert into products (product_id, category, price) values (883, 'Food - Baking', 4.89);
insert into products (product_id, category, price) values (884, 'Tools', 19.99);
insert into products (product_id, category, price) values (885, 'Pets', 6.99);
insert into products (product_id, category, price) values (886, 'Clothing - Tops', 14.99);
insert into products (product_id, category, price) values (887, 'Food - Dairy', 3.99);
insert into products (product_id, category, price) values (888, 'Food - Bakery', 3.29);
insert into products (product_id, category, price) values (889, 'Electronics', 89.99);
insert into products (product_id, category, price) values (890, 'Clothing - Tops', 29.99);
insert into products (product_id, category, price) values (891, 'Food - Bakery', 2.49);
insert into products (product_id, category, price) values (892, 'Food - Soups', 2.99);
insert into products (product_id, category, price) values (893, 'Food - Grains', 3.29);
insert into products (product_id, category, price) values (894, 'Garden', 14.99);
insert into products (product_id, category, price) values (895, 'Clothing - Shoes', 69.99);
insert into products (product_id, category, price) values (896, 'Food - Meat & Poultry', 5.99);
insert into products (product_id, category, price) values (897, 'Food - Condiments', 4.49);
insert into products (product_id, category, price) values (898, 'Food - Baking', 4.49);
insert into products (product_id, category, price) values (899, 'Kitchen', 19.99);
insert into products (product_id, category, price) values (900, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (901, 'Food - Frozen Foods', 5.49);
insert into products (product_id, category, price) values (902, 'Food - Produce', 3.99);
insert into products (product_id, category, price) values (903, 'Health', 89.99);
insert into products (product_id, category, price) values (904, 'Food - Fresh Produce', 0.75);
insert into products (product_id, category, price) values (905, 'Fitness', 15.99);
insert into products (product_id, category, price) values (906, 'Home', 29.99);
insert into products (product_id, category, price) values (907, 'Health', 59.99);
insert into products (product_id, category, price) values (908, 'Food - Frozen Meals', 14.99);
insert into products (product_id, category, price) values (909, 'Food - Canned Goods', 2.29);
insert into products (product_id, category, price) values (910, 'Outdoor', 29.99);
insert into products (product_id, category, price) values (911, 'Fitness', 25.99);
insert into products (product_id, category, price) values (912, 'Food - Cereal', 4.29);
insert into products (product_id, category, price) values (913, 'Food - Frozen', 6.99);
insert into products (product_id, category, price) values (914, 'Food - Sauces', 3.99);
insert into products (product_id, category, price) values (915, 'Food - Baking', 6.49);
insert into products (product_id, category, price) values (916, 'Home Security', 199.99);
insert into products (product_id, category, price) values (917, 'Garden', 45);
insert into products (product_id, category, price) values (918, 'Food - Condiments', 3.69);
insert into products (product_id, category, price) values (919, 'Outdoor', 89.99);
insert into products (product_id, category, price) values (920, 'Accessories', 49.99);
insert into products (product_id, category, price) values (921, 'Food - Frozen', 8.99);
insert into products (product_id, category, price) values (922, 'Accessories', 12.99);
insert into products (product_id, category, price) values (923, 'Home Appliances', 129.99);
insert into products (product_id, category, price) values (924, 'Food - Snacks', 3.49);
insert into products (product_id, category, price) values (925, 'Outdoor', 49.99);
insert into products (product_id, category, price) values (926, 'Food - Dressings', 3.49);
insert into products (product_id, category, price) values (927, 'Beauty', 54.99);
insert into products (product_id, category, price) values (928, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (929, 'Food - Condiments', 6.49);
insert into products (product_id, category, price) values (930, 'Food - Snacks', 1.39);
insert into products (product_id, category, price) values (931, 'Food - Snacks', 4.99);
insert into products (product_id, category, price) values (932, 'Food - Condiments', 3.69);
insert into products (product_id, category, price) values (933, 'Electronics', 15.99);
insert into products (product_id, category, price) values (934, 'Food - Salads', 5.99);
insert into products (product_id, category, price) values (935, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (936, 'Food - Jams & Jellies', 3.59);
insert into products (product_id, category, price) values (937, 'Outdoor', 59.99);
insert into products (product_id, category, price) values (938, 'Beauty', 22.99);
insert into products (product_id, category, price) values (939, 'Food - Beverages', 3.49);
insert into products (product_id, category, price) values (940, 'Food - Pasta', 3.79);
insert into products (product_id, category, price) values (941, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (942, 'Outdoor', 24.99);
insert into products (product_id, category, price) values (943, 'Food - Seafood', 8.49);
insert into products (product_id, category, price) values (944, 'Home', 129.99);
insert into products (product_id, category, price) values (945, 'Audio', 69.99);
insert into products (product_id, category, price) values (946, 'Food - Snacks', 5.49);
insert into products (product_id, category, price) values (947, 'Kitchen', 24.99);
insert into products (product_id, category, price) values (948, 'Food - Dairy', 5.49);
insert into products (product_id, category, price) values (949, 'Outdoor', 19.99);
insert into products (product_id, category, price) values (950, 'Home Improvement', 39.99);
insert into products (product_id, category, price) values (951, 'Food - Dairy Alternatives', 4.99);
insert into products (product_id, category, price) values (952, 'Fitness', 39.99);
insert into products (product_id, category, price) values (953, 'Toys', 10.99);
insert into products (product_id, category, price) values (954, 'Food - Soups', 2.99);
insert into products (product_id, category, price) values (955, 'Garden', 39.99);
insert into products (product_id, category, price) values (956, 'Home', 29.99);
insert into products (product_id, category, price) values (957, 'Kitchen', 49.99);
insert into products (product_id, category, price) values (958, 'Food - Frozen Foods', 7.99);
insert into products (product_id, category, price) values (959, 'Food - Pantry', 3.59);
insert into products (product_id, category, price) values (960, 'Home', 19.99);
insert into products (product_id, category, price) values (961, 'Home Improvement', 39.99);
insert into products (product_id, category, price) values (962, 'Outdoor', 299.99);
insert into products (product_id, category, price) values (963, 'Outdoor', 32.99);
insert into products (product_id, category, price) values (964, 'Fitness', 39.99);
insert into products (product_id, category, price) values (965, 'Clothing - Shirts', 39.99);
insert into products (product_id, category, price) values (966, 'Food - Snacks', 2.99);
insert into products (product_id, category, price) values (967, 'Home', 59.99);
insert into products (product_id, category, price) values (968, 'Food - Prepared Foods', 5.49);
insert into products (product_id, category, price) values (969, 'Pets', 6.99);
insert into products (product_id, category, price) values (970, 'Kitchen', 10.99);
insert into products (product_id, category, price) values (971, 'Clothing - Bottoms', 34.99);
insert into products (product_id, category, price) values (972, 'Beauty', 54.99);
insert into products (product_id, category, price) values (973, 'Food - Frozen', 1.99);
insert into products (product_id, category, price) values (974, 'Food - Seafood', 8.49);
insert into products (product_id, category, price) values (975, 'Food - Grains', 1.49);
insert into products (product_id, category, price) values (976, 'Pets', 24.99);
insert into products (product_id, category, price) values (977, 'Food - Grains', 3.59);
insert into products (product_id, category, price) values (978, 'Clothing - Activewear', 39.99);
insert into products (product_id, category, price) values (979, 'Kitchen', 39);
insert into products (product_id, category, price) values (980, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (981, 'Home', 17.99);
insert into products (product_id, category, price) values (982, 'Food - Frozen Foods', 4.99);
insert into products (product_id, category, price) values (983, 'Food - Snacks', 3.29);
insert into products (product_id, category, price) values (984, 'Food - Beverages', 3.99);
insert into products (product_id, category, price) values (985, 'Kitchen', 39.99);
insert into products (product_id, category, price) values (986, 'Food - Spices', 2.99);
insert into products (product_id, category, price) values (987, 'Food - Canned Goods', 3.29);
insert into products (product_id, category, price) values (988, 'Kitchen', 79.99);
insert into products (product_id, category, price) values (989, 'Food - Nuts', 6.99);
insert into products (product_id, category, price) values (990, 'Toys', 29.99);
insert into products (product_id, category, price) values (991, 'Automotive', 49.99);
insert into products (product_id, category, price) values (992, 'Food - Spices', 1.99);
insert into products (product_id, category, price) values (993, 'Food - Meat Substitutes', 5.89);
insert into products (product_id, category, price) values (994, 'Food - Snacks', 3.59);
insert into products (product_id, category, price) values (995, 'Home', 19.99);
insert into products (product_id, category, price) values (996, 'Food - Breakfast', 4.99);
insert into products (product_id, category, price) values (997, 'Automotive', 12.99);
insert into products (product_id, category, price) values (998, 'Food', 29.99);
insert into products (product_id, category, price) values (999, 'Food - Salads', 4.99);
insert into products (product_id, category, price) values (1000, 'Clothing - Pants', 54.99);
